import type { Metadata } from "next";
import Navbar from "@/components/navbar";

import "./globals.css";
import { AppProvider } from "@/context/AppContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      
    >
      <body>
        <AppProvider><Navbar/> 
        <main className="pt-20">
            {children}
          </main></AppProvider>
        </body>
    </html>
  );
}
